### PR TITLE
Redesign of the main page

### PR DESCRIPTION
**Pull request by noraa-junker**
## Overview

This PR:
* introduces a redesign for the mainpage  and the category overview page
* Changes readme to markdown file

## Images

image

image

### CODE REVIEW

**Comment by noraa-junker** [comment]
@cmb69 Speaker notes don't seem to work at all. Should I remove them or try to fix it?

**Comment by cmb69** [comment]
Apparently, talks.php.net is still regularly used by @rlerdorf and @derickr. Maybe they have something to say about this PR.

**Comment by derickr** [comment]
I really wouldn't bother about this beyond a redesign of the front page. It's pretty much legacy.

I run a local copy with a different renderer (from the `dericks-renderer` branch), and I think Rasmus uses his own generator too. I will be displeased if anything stops working.

**Comment by noraa-junker** [comment]
> I really wouldn't bother about this beyond a redesign of the front page. It's pretty much legacy.
> 
> I run a local copy with a different renderer (from the `dericks-renderer` branch), and I think Rasmus uses his own generator too. I will be displeased if anything stops working.

@derickr So you would be ok when the PR just changes the frontpage?

**Comment by noraa-junker** [comment]
@cmb69 @derickr  @rlerdorf I now just left the redesign of the main page in this PR. I hope like this it would be ok to merge it.

**Comment by noraa-junker** [comment]
Could I please get feedback on this.

**Comment by derickr** [comment]
Is the preview image in the PR up-to-date?

**Comment by noraa-junker** [comment]
> Is the preview image in the PR up-to-date?

@derickr Yes

**Comment by derickr** [comment]
Merged, thanks :-)

**Comment by derickr** [comment]
This does not seem to have worked, the pages only show the content, and none of the frames etc.

**Comment by derickr** [comment]
All sorted now :-)

**Comment by noraa-junker** [comment]
Thank you for merging it!

**Pull request merged**
